import path from "node:path";

import { syncKotlin, syncJavaScript, syncRepository, syncRust } from "./cli/sync";
import { parse, TranslatorJS, TranslatorKotlin, TranslatorTS } from "./index";
import { mkdir, readInkJSON, readTextFile, write } from "./cli/helpers";
import { TranslatorRust } from "./translators/rust";

async function main () {
  const args = process.argv.slice(2);
  const command = args.shift();

  switch (command) {
    case "sync": {
      await syncRepository();
      await syncJavaScript();
      await syncKotlin();
      await syncRust();
      break;
    }
    case "generate": {
      let header = `{} This file is generated by inklang, see <https://github.com/inklang/inklang>.\n{} Do not edit it directly since it'll be overwritten.\n\n`;

      const entrypoint = path.resolve("./src/main.ink");
      const code = await readTextFile(entrypoint);
      const statements = parse(code, entrypoint);

      switch (args.shift()) {
        case "javascript": {
          header = header.replaceAll("{}", "//");
          const cjs = header + new TranslatorJS(statements, "cjs").translate();
          const mjs = header + new TranslatorJS(statements, "mjs").translate();
          const dts = header + new TranslatorTS(statements).translate();

          await mkdir("generated/javascript");
          await write("generated/javascript/index.cjs", cjs);
          await write("generated/javascript/index.mjs", mjs);
          await write("generated/javascript/index.d.ts", dts);

          break;
        }
        case "kotlin": {
          header = header.replaceAll("{}", "//");
          const code = header + new TranslatorKotlin(statements).translate();

          const inkJSON = await readInkJSON();
          const libSubPath = inkJSON.package.replace(/\./g, "/");

          const libDir = `generated/kotlin/src/main/${libSubPath}`;
          await mkdir(libDir);
          await write(`${libDir}/${inkJSON.displayName}.kt`, code);

          break;
        }
        case "rust": {
          header = header.replaceAll("{}", "//!");
          const code = header + new TranslatorRust(statements).translate();

          await mkdir("generated/rust");
          await write("generated/rust/lib.rs", code);

          break;
        }
        default: {
          throw new Error(`unknown language: javascript, kotlin, rust`);
        }
      }

      break;
    }
    default: {
      throw new Error(`unknown command, available: sync, generate`);
    }
  }
}

main();
